import os
import torch as th
import torch.nn as nn
import tqdm


class PBar(object):
    """
    定义一个显示进度条的类
    """
    def __enter__(self):
        self.t = None
        return self

    def __call__(self, blockno, readsize, totalsize):
        """
        __init__相当于构造函数, 声明类的实例对象时调用
        __enter__将类用with语句声明时调用，对象赋给as后面定义的变量
        __exit__是with语句执行完后调用
        __del__相当于析构函数
        __call__ 函数，是类可以被当做一个实例对象做参数给其他函数使用，定义具体的实现方式
        """
        if self.t is None:
            self.t = tqdm.tqdm(total=totalsize)
        self.t.update(readsize)

    def __exit__(self, exc_type, exc_value, traceback):
        self.t.close()


class AminerDataset(object):
    """
    Download Aminer Dataset from Amazon S3 bucket. 
    """
    def __init__(self, path):

        self.url = 'https://data.dgl.ai/dataset/aminer.zip'

        if not os.path.exists(os.path.join(path, 'aminer.txt')):
            print('File not found. Downloading from', self.url)
            self._download_and_extract(path, 'aminer.zip')
        self.fn = os.path.join(path, 'aminer.txt')

    def _download_and_extract(self, path, filename):
        import shutil, zipfile, zlib
        from tqdm import tqdm
        import urllib.request

        # 下载
        fn = os.path.join(path, filename)
        with PBar() as pb:
            urllib.request.urlretrieve(self.url, fn, pb)
        print('Download finished. Unzipping the file...')

        # 解压
        with zipfile.ZipFile(fn) as zf:
            zf.extractall(path)
        print('Unzip finished.')


class CustomDataset(object):
    """
    Custom dataset generated by sampler.py (e.g. NetDBIS)
    """
    def __init__(self, path):
        self.fn = path
